Repository marzneshin/marzneshin, pull requests merged in 2024-02, with the labels that each got.

#18 feat: services page with table and dialog
  app/dashboard/.prettierignore
  app/dashboard/.prettierrc.json
  app/dashboard/public/locales/en.json
  app/dashboard/src/components/DeleteNodeModal.tsx
  app/dashboard/src/components/DeleteUserModal.tsx
  app/dashboard/src/components/Dialog/Icons.tsx
  app/dashboard/src/components/Dialog/ModalFooter.tsx
  app/dashboard/src/components/Dialog/ModalHeader.tsx
  app/dashboard/src/components/Dialog/index.tsx
  app/dashboard/src/components/HostsDialog.tsx
  app/dashboard/src/components/ListCheckBox/index.tsx
  app/dashboard/src/components/NodesModal.tsx
  app/dashboard/src/components/Pagination.tsx
  app/dashboard/src/components/ServiceDialog/DefaultValues.ts
  app/dashboard/src/components/ServiceDialog/FormSchema.ts
  app/dashboard/src/components/ServiceDialog/InboundsField.tsx
  app/dashboard/src/components/ServiceDialog/InboundsSelectList.tsx
  app/dashboard/src/components/ServiceDialog/NameField.tsx
  app/dashboard/src/components/ServiceDialog/index.tsx
  app/dashboard/src/components/ServicesFilters.tsx
  app/dashboard/src/components/ServicesTable.tsx
  app/dashboard/src/components/UserDialog/ModalFooter.tsx
  app/dashboard/src/components/UserDialog/ServicesField.tsx
  app/dashboard/src/components/UserDialog/ServicesSelectList.tsx
  app/dashboard/src/components/UserDialog/UserDialogIcons.ts
  app/dashboard/src/components/UserDialog/index.tsx
  app/dashboard/src/components/UsersFilters.tsx
  app/dashboard/src/components/UsersTable.tsx
  app/dashboard/src/components/UsersTable/EmptySection.tsx
  app/dashboard/src/components/UsersTable/Icons.ts
  app/dashboard/src/components/UsersTable/StatusSortSelect.tsx
  app/dashboard/src/components/UsersTable/UsageSlider.tsx
  app/dashboard/src/components/UsersTable/index.tsx
  app/dashboard/src/contexts/DashboardContext.tsx
  app/dashboard/src/pages/Login.tsx
  app/dashboard/src/pages/Services.tsx
  app/dashboard/src/pages/Users.tsx
  app/dashboard/src/types/Service.ts
  app/dashboard/src/utils/userPreferenceStorage.ts
  app/models/service.py
  app/models/user.py
Labels: enhancement, refactor, improvement

#33 chore: remove debugging state viewer for react form plugin
  app/dashboard/src/components/ServiceDialog/index.tsx
Labels: invalid, task

#36 update: scaffold refactoring branch to master
  app/dashboard/src/components/ListCheckBox/index.tsx
  app/dashboard/src/components/ServiceDialog/InboundsField.tsx
  app/dashboard/src/components/ServiceDialog/index.tsx
  app/dashboard/src/components/UserDialog/ServicesField.tsx
  app/dashboard/src/constants/Project.ts
  config.py
Labels: task

#38 fix: Sidebar dark mode
  app/dashboard/src/components/Sidebar/index.tsx
Labels: bug, improvement

#40 fix: auto navigation to login page
  app/dashboard/src/App.tsx
  app/dashboard/src/contexts/AdminContext.tsx
  app/dashboard/src/pages/Login.tsx
Labels: bug, refactor, improvement

#44 [FIX] users links/configs
  app/db/crud.py
  app/db/migrations/versions/20faa9f18c0a_init.py
  app/db/models.py
  app/marznode/grpc.py
  app/models/proxy.py
  app/models/user.py
  app/utils/share.py
Labels: bug, backend

#50 refact: spliting the monolithc state manager
  app/dashboard/src/components/CoreSettingsModal.tsx
  app/dashboard/src/components/DeleteUserModal.tsx
  app/dashboard/src/components/Footer.tsx
  app/dashboard/src/components/Header.tsx
  app/dashboard/src/components/HostsDialog.tsx
  app/dashboard/src/components/NodesModal.tsx
  app/dashboard/src/components/NodesUsage.tsx
  app/dashboard/src/components/QRCodeDialog.tsx
  app/dashboard/src/components/ResetAllUsageModal.tsx
  app/dashboard/src/components/ResetUserUsageModal.tsx
  app/dashboard/src/components/RevokeSubscriptionModal.tsx
  app/dashboard/src/components/ServiceDialog/InboundsField.tsx
  app/dashboard/src/components/ServiceDialog/InboundsSelectList.tsx
  app/dashboard/src/components/ServiceDialog/index.tsx
  app/dashboard/src/components/ServicesFilters.tsx
  app/dashboard/src/components/ServicesTable/index.tsx
  app/dashboard/src/components/Table/EmptySection.tsx
  app/dashboard/src/components/Table/Icons.ts
  app/dashboard/src/components/Table/Pagination.tsx
  app/dashboard/src/components/Table/Sort.tsx
  app/dashboard/src/components/UsageFilter.tsx
  app/dashboard/src/components/UserDialog/index.tsx
  app/dashboard/src/components/UsersFilters.tsx
  app/dashboard/src/components/UsersTable/StatusSortSelect.tsx
  app/dashboard/src/components/UsersTable/index.tsx
  app/dashboard/src/contexts/AdminContext.ts
  app/dashboard/src/contexts/CoreSettingsContext.ts
  app/dashboard/src/contexts/DashboardContext.ts
  app/dashboard/src/contexts/DashboardContext.tsx
  app/dashboard/src/contexts/HostsContext.ts
  app/dashboard/src/contexts/InboundsContext.ts
  app/dashboard/src/contexts/NodesContext.ts
  app/dashboard/src/contexts/ServicesContext.ts
  app/dashboard/src/contexts/UsersContext.ts
  app/dashboard/src/pages/Dashboard.tsx
  app/dashboard/src/pages/Services.tsx
  app/dashboard/src/pages/Users.tsx
  app/dashboard/src/types/Filter.ts
  app/dashboard/src/types/Inbounds.ts
  app/dashboard/src/types/Protocol.ts
  app/dashboard/src/types/User.ts
Labels: refactor, improvement, frontend

#53 feat: better subscription links
  app/db/crud.py
  app/db/migrations/versions/20faa9f18c0a_init.py
  app/db/models.py
  app/marznode/operations.py
  app/models/user.py
  app/utils/jwt.py
  app/utils/notification.py
  app/views/subscription.py
  app/views/user.py
Labels: enhancement, improvement

#55 fix: getting and updating hosts is now functional
  app/db/crud.py
  app/marzneshin.py
  app/marznode/operations.py
  app/models/proxy.py
  app/routes/__init__.py
  app/routes/admin.py
  app/routes/inbounds.py
  app/routes/node.py
  app/routes/service.py
  app/routes/subscription.py
  app/routes/system.py
  app/routes/user.py
Labels: bug, improvement, backend

#57 refactor: better database structure
  app/db/migrations/versions/20faa9f18c0a_init.py
  app/db/models.py
  app/models/user.py
Labels: refactor, improvement

#60 fix: services update and delete
  app/dashboard/public/locales/en.json
  app/dashboard/src/components/DeleteServiceModal.tsx
  app/dashboard/src/components/NodesModal.tsx
  app/dashboard/src/components/ServiceDialog/NameField.tsx
  app/dashboard/src/components/ServiceDialog/index.tsx
  app/dashboard/src/pages/Services.tsx
Labels: bug

#85 refactor: better synchronization with marznode
  app/db/crud.py
  app/db/migrations/versions/20faa9f18c0a_init.py
  app/db/models.py
  app/marzneshin.py
  app/marznode/__init__.py
  app/marznode/base.py
  app/marznode/database.py
  app/marznode/grpc.py
  app/marznode/grpcio.py
  app/marznode/grpclib.py
  app/marznode/marznode.proto
  app/marznode/marznode_grpc.py
  app/marznode/marznode_pb2.py
  app/marznode/marznode_pb2.pyi
  app/marznode/marznode_pb2_grpc.py
  app/marznode/operations.py
  app/models/node.py
  app/models/user.py
  app/routes/node.py
  app/routes/user.py
  app/tasks/__init__.py
  app/tasks/nodes.py
  app/tasks/record_usages.py
Labels: bug, enhancement, improvement

#88 Fix: user and service modification
  app/marznode/operations.py
  app/models/admin.py
  app/models/user.py
  app/routes/service.py
  app/routes/user.py
  app/tasks/reset_user_data_usage.py
Labels: bug

#101 refact/table component
  app/dashboard/src/components/header/github-button.tsx
  app/dashboard/src/components/header/index.tsx
  app/dashboard/src/components/table/handle-sort.ts
  app/dashboard/src/components/table/index.tsx
  app/dashboard/src/pages/nodes/table/action-buttons.tsx
  app/dashboard/src/pages/nodes/table/index.tsx
  app/dashboard/src/pages/services/table.tsx
  app/dashboard/src/pages/users/table/action-buttons.tsx
  app/dashboard/src/pages/users/table/index.tsx
Labels: refactor, frontend

#102 improve: separate codeql runnner for API and Dashboard
  .github/workflows/api-ci.yml
  .github/workflows/api-codeql.yml
  .github/workflows/dashboard-codeql.yml
Labels: improvement, continuous-integration
