Repository marzneshin/marzneshin, pull requests merged in 2024-06, with the labels that each got.

#344 style(nodes-log): green color when xray log container is connected to the node
  dashboard/src/features/nodes/log/container.tsx
Labels: improvement, frontend

#337 improve(nodes): handling nodes and database connection
  app/db/migrations/versions/058eb11c5b17_user_reset_in_table.py
  app/marznode/grpcio.py
  app/marznode/operations.py
  app/models/node.py
  app/routes/service.py
Labels: improvement, backend

#343 fix(user-editing): avoid forced value set while editing user for expiration method and datalimit field
  .gitignore
  dashboard/src/features/users/components/used-user-traffic.tsx
  dashboard/src/features/users/dialogs/mutation/fields/data-limit.tsx
  dashboard/src/features/users/dialogs/mutation/fields/onhold-expire-duration.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
  dashboard/src/features/users/dialogs/mutation/sections/data-limit.tsx
  dashboard/src/features/users/dialogs/mutation/sections/expiration-method.tsx
  dashboard/src/features/users/dialogs/mutation/sections/use-expiration-method-tabs.ts
  dashboard/src/features/users/types/index.ts
Labels: bug

#349 fix(hosts-edit): set the port to null when its empty string
  dashboard/public/locales/en.json
  dashboard/src/features/hosts/dialogs/mutation/index.tsx
  dashboard/src/features/hosts/dialogs/settings/index.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/columns.tsx
Labels: bug

#323 refactor: remove extra validators
  app/models/proxy.py
Labels: refactor, backend

#355 ci(ui-testing): UI testing, storybook
  .github/workflows/chromatic-deploy.yml
  .github/workflows/chromatic.yml
  .github/workflows/dashboard-ci.yml
  dashboard/.eslintrc.cjs
  dashboard/.gitignore
  dashboard/.storybook/main.ts
  dashboard/.storybook/preview.tsx
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/src/components/ui/button.tsx
  dashboard/src/components/ui/button/button.stories.tsx
  dashboard/src/components/ui/button/index.tsx
  dashboard/src/features/nodes/log/container.tsx
  dashboard/src/globals.css
  dashboard/src/routeTree.gen.ts
  dashboard/tailwind.config.js
Labels: docs, ci, cd, frontend, quality-assurance, user-experience

#356 ci: add permission chromatic-deploy.yml
  .github/workflows/chromatic-deploy.yml
Labels: ci, cd

#359 feat(support-us): support us card in sidebar
  .github/workflows/dashboard-ci.yml
  dashboard/.storybook/main.ts
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/locales/en.json
  dashboard/src/components/entity-table/tests/columns.mock.tsx
  dashboard/src/components/entity-table/tests/data.mock.ts
  dashboard/src/components/entity-table/tests/dialogs.mock.tsx
  dashboard/src/components/entity-table/tests/entity-table.test.tsx
  dashboard/src/components/entity-table/tests/fetch-entity.mock.ts
  dashboard/src/components/index.ts
  dashboard/src/components/sidebar/sidebar-footer.tsx
  dashboard/src/components/support-us/index.tsx
  dashboard/src/components/support-us/support-us.stories.tsx
  dashboard/src/components/support-us/support-us.test.tsx
  dashboard/src/components/support-us/types.ts
  dashboard/src/components/support-us/use-support-us.test.ts
  dashboard/src/components/support-us/use-support-us.ts
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/test-runner-jest.config.js
  dashboard/vitest.config.ts
  dashboard/vitest.setup.ts
Labels: docs, feature, improvement, ci, quality-assurance

#358 feat: remove .env admins
  .env.example
  README.md
  app/dependencies.py
  app/models/user.py
  app/routes/admin.py
  app/utils/jwt.py
  config.py
Labels: backend, security

#364 Improve(users-stats): responsiveness, code-reusability
  dashboard/src/components/charts/index.ts
  dashboard/src/components/charts/pie/index.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/stats-widgets/mini-widget/index.tsx
  dashboard/src/components/widgets/index.ts
  dashboard/src/components/widgets/mini-widget/index.tsx
  dashboard/src/features/users/services/index.ts
  dashboard/src/features/users/widgets/users-stats-widget/index.tsx
  dashboard/src/features/users/widgets/users-stats-widget/legend.tsx
  dashboard/src/features/users/widgets/users-stats-widget/users-stats-widget.stories.ts
  dashboard/src/routes/_dashboard/index.tsx
Labels: refactor, frontend, responsiveness

#365 chore(readme): real apps screenshot instead of dead apps
  README.md
  docs/assets/Desktop-full.png
Labels: docs

#374 feat(role-based-nonsudo-ui): role based UI nonsudo
  app/db/crud.py
  app/models/admin.py
  app/routes/admin.py
  app/routes/service.py
  dashboard/src/features/auth/auth.store.ts
  dashboard/src/features/auth/login/form.tsx
  dashboard/src/features/search-command/command-box.tsx
  dashboard/src/features/sidebar/items.tsx
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/src/features/sudo-routes/index.tsx
  dashboard/src/routes/_dashboard/hosts.lazy.tsx
  dashboard/src/routes/_dashboard/nodes.lazy.tsx
  dashboard/src/routes/_dashboard/services.lazy.tsx
  dashboard/src/routes/_dashboard/settings.lazy.tsx
Labels: feature, frontend, backend, feat:sidebar, feat:multiadmin

#375 refact(dashboard-header): centered search box
  dashboard/.storybook/preview-head.html
  dashboard/package.json
  dashboard/src/components/header/header.stories.tsx
  dashboard/src/components/header/header.tsx
  dashboard/src/components/header/index.ts
  dashboard/src/components/header/index.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/logo/index.tsx
  dashboard/src/components/page/index.tsx
  dashboard/src/features/footer/index.tsx
  dashboard/src/routes/_dashboard.tsx
Labels: refactor, frontend

#376 improve(version): display full version for both dev and prod
  .github/workflows/dashboard-ci.yml
  Dockerfile
  dashboard/src/components/page/index.tsx
  dashboard/src/features/footer/index.tsx
  dashboard/vite.config.ts
Labels: improvement, frontend

#377 ci(dashboard): fix dashbaord ci id step for get version (pr, main)
  .github/workflows/dashboard-ci.yml
Labels: invalid, ci

#378 fix: version display non-head
  dashboard/src/features/footer/index.tsx
  dashboard/vite.config.ts
Labels: invalid, improvement, ci

#381 feat(sidebar-hosts-entity-table): providing mobile responsive sidebar and dropdown inbounds selection
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/src/components/entity-table/table.tsx
  dashboard/src/components/index.ts
  dashboard/src/features/entity-table/components/index.ts
  dashboard/src/features/entity-table/components/sidebar-entity-card.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-popover.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
  dashboard/src/features/entity-table/components/table-filtering.tsx
  dashboard/src/features/entity-table/components/table-pagination.tsx
  dashboard/src/features/entity-table/components/table.tsx
  dashboard/src/features/entity-table/contexts/entity-table-provider.ts
  dashboard/src/features/entity-table/contexts/index.ts
  dashboard/src/features/entity-table/contexts/sidebar-entity-table-provider.ts
  dashboard/src/features/entity-table/entity-table.tsx
  dashboard/src/features/entity-table/hooks/index.ts
  dashboard/src/features/entity-table/hooks/use-dialog.ts
  dashboard/src/features/entity-table/hooks/use-entity-query.ts
  dashboard/src/features/entity-table/hooks/use-entity-table.ts
  dashboard/src/features/entity-table/hooks/use-filtering.ts
  dashboard/src/features/entity-table/hooks/use-pagination.ts
  dashboard/src/features/entity-table/hooks/use-row-selection.ts
  dashboard/src/features/entity-table/hooks/use-sidebar-entity-table.ts
  dashboard/src/features/entity-table/hooks/use-sorting.ts
  dashboard/src/features/entity-table/hooks/use-visibility.ts
  dashboard/src/features/entity-table/index.ts
  dashboard/src/features/entity-table/sidebar-entity-table.tsx
  dashboard/src/features/entity-table/stories/columns-fns.tsx
  dashboard/src/features/entity-table/stories/entity-table.stories.tsx
  dashboard/src/features/entity-table/stories/fetch-entities.ts
  dashboard/src/features/hosts/services/hosts.query.ts
  dashboard/src/features/hosts/tables/inbound-hosts/inbound-sidebar-card.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/inbound.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/index.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/table.tsx
  dashboard/src/features/nodes/services/nodes.query.ts
  dashboard/src/features/nodes/tables/table.tsx
  dashboard/src/features/services/services/services.query.ts
  dashboard/src/features/services/tables/services/index.tsx
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/src/features/support-us/index.tsx
  dashboard/src/features/support-us/support-us.stories.tsx
  dashboard/src/features/support-us/support-us.test.tsx
  dashboard/src/features/support-us/types.ts
  dashboard/src/features/support-us/use-support-us.test.ts
  dashboard/src/features/support-us/use-support-us.ts
  dashboard/src/features/users/services/users.query.ts
  dashboard/src/features/users/tables/users/index.tsx
Labels: feature, refactor, improvement, feat:data-entity-table

#382 improve(users-creation): show skeleton when loading and alert box when no service is available
  dashboard/src/features/users/dialogs/mutation/fields/services.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: improvement, frontend, user-experience

#383 refact(users-mutation-expire-field): Smiplify user mutation expire fields for determined, onhold and unlimited type
  dashboard/public/locales/en.json
  dashboard/src/features/users/components/dialogs/delete-confirmation/index.tsx
  dashboard/src/features/users/components/dialogs/index.ts
  dashboard/src/features/users/components/dialogs/mutation/fields/data-limit-reset-strategy.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/data-limit.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/expire-date.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/index.ts
  dashboard/src/features/users/components/dialogs/mutation/fields/note.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/onhold-expire-duration.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/onhold-timeout.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/services.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/username.tsx
  dashboard/src/features/users/components/dialogs/mutation/index.tsx
  dashboard/src/features/users/components/dialogs/mutation/schema.ts
  dashboard/src/features/users/components/dialogs/mutation/sections/data-limit/index.tsx
  dashboard/src/features/users/components/dialogs/mutation/sections/data-limit/use-data-limit.ts
  dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/index.tsx
  dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/use-expiration-method-tabs.ts
  dashboard/src/features/users/components/dialogs/mutation/sections/index.ts
  dashboard/src/features/users/components/dialogs/settings/index.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/index.ts
  dashboard/src/features/users/components/dialogs/settings/user-info/qrcode.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/subcription-link-button.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/subscription-actions.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/user-status-enable-button.tsx
  dashboard/src/features/users/components/index.ts
  dashboard/src/features/users/components/tables/index.ts
  dashboard/src/features/users/components/tables/services/columns.tsx
  dashboard/src/features/users/components/tables/services/index.tsx
  dashboard/src/features/users/components/tables/users/columns.tsx
  dashboard/src/features/users/components/tables/users/index.tsx
  dashboard/src/features/users/components/widgets/index.ts
  dashboard/src/features/users/components/widgets/users-stats-widget/index.tsx
  dashboard/src/features/users/components/widgets/users-stats-widget/legend.tsx
  dashboard/src/features/users/components/widgets/users-stats-widget/users-stats-widget.stories.ts
  dashboard/src/features/users/contexts/router.ts
  dashboard/src/features/users/dialogs/mutation/sections/data-limit.tsx
  dashboard/src/features/users/dialogs/mutation/sections/use-expiration-method-tabs.ts
  dashboard/src/features/users/index.ts
Labels: refactor

#390 fix(users-stats): total value delivered by api instead of calculating it
  dashboard/src/features/users/components/widgets/users-stats-widget/index.tsx
  dashboard/src/features/users/components/widgets/users-stats-widget/users-stats-widget.stories.ts
Labels: bug, frontend

#391 chore(issue-templates): bug report and feature request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_story.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr_validation.yml
  README.md
  app/config/env.py
  app/models/user.py
  dashboard/public/locales/ckb.json
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/public/locales/kmr.json
  dashboard/public/locales/kur.json
  dashboard/src/features/users/components/dialogs/settings/user-info/subscription-actions.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/subscription-link-button.tsx
  dashboard/src/features/users/components/used-user-traffic.tsx
Labels: docs, improvement, task

#394 refact(backend-lifespan): improving type checking and incorporating lifespan as an alternative to on_event
  app/dependencies.py
  app/marzneshin.py
  app/routes/admin.py
  app/routes/inbounds.py
  cli/admin.py
  cli/subscription.py
  cli/user.py
  cli/utils.py
  marzneshin-cli.py
Labels: refactor, backend

#398 fix(users-settings): Spliting info section into subscription tab and info tab
  .github/workflows/pr_validation.yml
  dashboard/src/components/copy-button/index.tsx
  dashboard/src/features/users/components/dialogs/settings/index.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/subscription-actions.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/subscription-link-button.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/user-status-enable-button.tsx
Labels: improvement, frontend, user-experience

#392 feat(mobile-navgiation): bottom menu for sudo admin and admin
  dashboard/src/components/page/index.tsx
  dashboard/src/features/bottom-menu/index.tsx
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/src/features/sidebar/toggle.tsx
  dashboard/src/features/version-indicator/index.tsx
  dashboard/src/hooks/index.ts
  dashboard/src/hooks/use-is-current-route.ts
  dashboard/src/routes/_dashboard.tsx
Labels: feature, refactor, improvement, frontend, feat:sidebar
