Repository marzneshin/marzneshin, pull requests merged in 2024-08, with the labels that each got.

#475 chore(readme): migrating to docs
  CONTRIBUTING.md
  README.md
  cli/README.md
Labels: docs, improvement, task

#476 fix(stats): filter removed users from the count query
  app/db/crud.py
Labels: bug

#474 feat(multi-backend-node): hysteria and multi-backend node management
  .github/workflows/dashboard-ci.yml
  app/db/__init__.py
  app/db/crud.py
  app/db/migrations/versions/35774c98f945_add_node_backends.py
  app/db/models.py
  app/marznode/base.py
  app/marznode/database.py
  app/marznode/grpcio.py
  app/marznode/grpclib.py
  app/marznode/marznode.proto
  app/marznode/marznode_grpc.py
  app/marznode/marznode_pb2.py
  app/marznode/marznode_pb2.pyi
  app/marznode/marznode_pb2_grpc.py
  app/models/node.py
  app/routes/node.py
  dashboard/public/locales/en.json
  dashboard/src/components/settings-dialog/index.tsx
  dashboard/src/features/admins/components/dialogs/settings/index.tsx
  dashboard/src/features/hosts/dialogs/settings/index.tsx
  dashboard/src/features/nodes/dialogs/settings/index.tsx
  dashboard/src/features/nodes/dialogs/settings/node-backend-setting.tsx
  dashboard/src/features/nodes/dialogs/settings/node-config-editor.tsx
  dashboard/src/features/nodes/dialogs/settings/use-nodes-settings.ts
  dashboard/src/features/nodes/log/container.tsx
  dashboard/src/features/nodes/services/backend-stats.query.ts
  dashboard/src/features/nodes/services/index.ts
  dashboard/src/features/nodes/services/logs.socket.ts
  dashboard/src/features/nodes/services/nodes.query.ts
  dashboard/src/features/nodes/services/settings.mutate.ts
  dashboard/src/features/nodes/services/settings.query.ts
  dashboard/src/features/nodes/types/index.ts
  dashboard/src/features/services/components/dialogs/settings.dialog.tsx
  dashboard/src/features/users/components/dialogs/settings/index.tsx
  package.json
  pnpm-lock.yaml
  requirements.txt
Labels: feature, frontend, backend

#481 fix(editor-empty-while-fetching): await editor config loading while fetching
  dashboard/src/components/awaiting/index.tsx
  dashboard/src/features/nodes/dialogs/settings/node-config-editor.tsx
  dashboard/src/features/nodes/dialogs/settings/use-nodes-settings.ts
Labels: bug, refactor, improvement, frontend

#484 fix(users-dialog): assign the default expiration strategy value
  dashboard/src/components/form-fields/date.tsx
  dashboard/src/features/users/components/dialogs/mutation/index.tsx
Labels: bug, improvement

#487 fix(inbounds-popover): lowering the size of inbounds popover
  dashboard/src/features/entity-table/components/sidebar-entity-popover.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
Labels: bug, improvement, frontend, user-experience

#485 feat(hosts): weight and sorting
  app/db/crud.py
  app/db/migrations/versions/fd423c19f682_add_weight_to_host.py
  app/db/models.py
  app/models/proxy.py
  app/utils/share.py
  dashboard/public/locales/en.json
  dashboard/src/features/hosts/dialogs/mutation/fields/index.ts
  dashboard/src/features/hosts/dialogs/mutation/fields/weight.tsx
  dashboard/src/features/hosts/dialogs/mutation/index.tsx
  dashboard/src/features/hosts/schema/hosts-schema.ts
  requirements.txt
Labels: feature, frontend, backend

#486 feat(users-settings): adding created at and online at with time
  dashboard/biome.json
  dashboard/public/locales/en.json
  dashboard/src/components/info-table/date-table-row.tsx
  dashboard/src/components/settings-dialog/index.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx
  dashboard/src/features/users/components/tables/users/columns.tsx
Labels: feature, improvement, frontend

#492 fix(settings-dialog-scroll): determining the size of screen for smaller vertical size with less bottom gap
  dashboard/src/components/settings-dialog/index.tsx
Labels: bug, improvement, frontend, user-experience

#493 fix(templates): specify some detours correctly in sing-box template
  app/templates/sing-box.json
Labels: backend

#494 refact(support-us): simplifying component variant logic and component composition
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/src/features/support-us/card.tsx
  dashboard/src/features/support-us/donation-button.tsx
  dashboard/src/features/support-us/index.tsx
  dashboard/src/features/support-us/popover.tsx
  dashboard/src/features/support-us/support-us.stories.tsx
  dashboard/src/features/support-us/support-us.test.tsx
Labels: refactor, frontend

#499 improve(nodes-settings): show an alert when there is no backend configured for the node
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/src/components/alert-card/index.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/ui/alert.tsx
  dashboard/src/features/nodes/dialogs/settings/index.tsx
  dashboard/src/features/users/components/no-service-alert/index.tsx
  dashboard/src/routes/_dashboard/nodes.lazy.tsx
Labels: bug, improvement, frontend, user-experience

#500 improve(user-info-last-use): human readable date
  app/models/user.py
  dashboard/public/locales/en.json
  dashboard/src/features/users/components/dialogs/settings/index.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx
  dashboard/src/features/users/components/dialogs/settings/user-info/user-status-enable-button.tsx
  dashboard/src/features/users/types/user.ts
Labels: feature, refactor, improvement, frontend

#495 chore(repo-migration): links, names, descriptions to be prepared for repo migration
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  dashboard/src/utils/project-info.ts
  script.sh
  tools/service-install.sh
Labels: docs, task

#506 fix(translations): farsi node removal message
  dashboard/public/locales/fa.json
  dashboard/src/features/nodes/tables/detail-table/index.tsx
Labels: bug, improvement, frontend, translation

#513 feat(users/entity-table): filtering the users based on admin for each admin
  dashboard/public/locales/en.json
  dashboard/src/components/data-table/index.ts
  dashboard/src/components/data-table/pagination.tsx
  dashboard/src/components/index.ts
  dashboard/src/features/admins/components/tables/admins/columns.tsx
  dashboard/src/features/admins/components/tables/admins/index.tsx
  dashboard/src/features/admins/services/admins.query.ts
  dashboard/src/features/entity-table/components/actions-cell.tsx
  dashboard/src/features/entity-table/components/column-header-combo-filter.tsx
  dashboard/src/features/entity-table/components/column-header.tsx
  dashboard/src/features/entity-table/components/data-table.tsx
  dashboard/src/features/entity-table/components/index.ts
  dashboard/src/features/entity-table/components/sidebar-entity-card.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-popover.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
  dashboard/src/features/entity-table/components/table-filtering.tsx
  dashboard/src/features/entity-table/components/table-pagination.tsx
  dashboard/src/features/entity-table/components/table-view-option.tsx
  dashboard/src/features/entity-table/components/table.tsx
  dashboard/src/features/entity-table/contexts/entity-table-provider.tsx
  dashboard/src/features/entity-table/entity-table.tsx
  dashboard/src/features/entity-table/hooks/index.ts
  dashboard/src/features/entity-table/hooks/use-entity-query.ts
  dashboard/src/features/entity-table/hooks/use-filtering.ts
  dashboard/src/features/entity-table/hooks/use-primary-filtering.ts
  dashboard/src/features/entity-table/hooks/use-sidebar-entity-table.ts
  dashboard/src/features/entity-table/index.ts
  dashboard/src/features/entity-table/sidebar-entity-table.tsx
  dashboard/src/features/entity-table/stories/entity-table.stories.tsx
  dashboard/src/features/hosts/services/hosts.query.ts
  dashboard/src/features/hosts/tables/inbound-hosts/columns.tsx
  dashboard/src/features/nodes/dialogs/settings/node-backend-setting.tsx
  dashboard/src/features/nodes/services/nodes.query.ts
  dashboard/src/features/nodes/tables/columns.tsx
  dashboard/src/features/nodes/tables/table.tsx
  dashboard/src/features/services/components/tables/inbounds/columns.tsx
  dashboard/src/features/services/components/tables/inbounds/index.tsx
  dashboard/src/features/services/components/tables/services/columns.tsx
  dashboard/src/features/services/components/tables/services/index.tsx
  dashboard/src/features/services/components/tables/users/columns.tsx
  dashboard/src/features/services/components/tables/users/index.tsx
  dashboard/src/features/services/services/services.query.ts
  dashboard/src/features/users/components/tables/services/columns.tsx
  dashboard/src/features/users/components/tables/services/index.tsx
  dashboard/src/features/users/components/tables/users/columns.tsx
  dashboard/src/features/users/components/tables/users/index.tsx
  dashboard/src/features/users/services/users.query.ts
Labels: feature, frontend, feat:data-entity-table, feat:multiadmin

#507 improve(entity-tables): reverse entity sorting based on creation date-time
  dashboard/src/features/entity-table/entity-table.tsx
Labels: improvement, frontend, user-experience, feat:data-entity-table

#536 feat(entity-table/filtered-columns): fitler icon to indicate a column is filterable
  dashboard/src/features/entity-table/components/column-header-combo-filter.tsx
Labels: feature, improvement, frontend, user-experience, feat:data-entity-table

#520 fix(github-repo-stats): oversized github logo icon for safari browsers
  dashboard/src/features/github-repo/github-repo.tsx
Labels: bug, frontend, user-experience

#543 fix(api): user usage reset
  app/routes/user.py
Labels: bug, backend
