Repository marzneshin/marzneshin, pull requests merged in 2024-05, with the labels that each got.

#241 fix: browser crash while switching expiration method
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: bug, frontend

#242 improve: optional expiration date for unlimited on hold
  dashboard/src/features/users/dialogs/mutation/index.tsx
  dashboard/src/features/users/dialogs/mutation/schema.ts
  dashboard/src/features/users/types/index.ts
Labels: improvement

#243 improve(users-data-limit): unlimited and limited option for data limit
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: improvement

#244 improve: sorani latin translation on users page
  dashboard/public/locales/kur.json
Labels: documentation

#245 fix: services select undefined
  dashboard/public/locales/kur.json
  dashboard/src/features/users/components/services-card.tsx
  dashboard/src/features/users/dialogs/mutation/fields/data-limit-reset-strategy.tsx
  dashboard/src/features/users/dialogs/mutation/fields/services.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: frontend

#246 fix: user creation dialog when data limit and expire are unlimited
  app/models/user.py
  dashboard/src/features/users/dialogs/mutation/index.tsx
  dashboard/src/features/users/dialogs/mutation/schema.ts
Labels: bug, frontend, backend

#233 feat(users-status): separate user enabled from user status and toggle the user status in settings page
  app/db/crud.py
  app/db/migrations/versions/20faa9f18c0a_init.py
  app/db/migrations/versions/e8325f600a49_user_enable.py
  app/db/models.py
  app/models/user.py
  app/routes/user.py
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/features/users/components/users-status.tsx
  dashboard/src/features/users/dialogs/settings/user-info/index.ts
  dashboard/src/features/users/dialogs/settings/user-info/table.tsx
  dashboard/src/features/users/dialogs/settings/user-info/user-status-enable-button.tsx
  dashboard/src/features/users/services/index.ts
  dashboard/src/features/users/services/user-status.mutate.ts
  dashboard/src/features/users/types/index.ts
Labels: enhancement, frontend, backend

#247 fix: translation file path for dashboard and different compilation
  .env.example
  app/marzneshin.py
  config.py
  dashboard/src/features/i18n/index.ts
  dashboard/vite.config.ts
  makefile
Labels: frontend

#250 fix: xray config update undefined
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/features/nodes/dialogs/settings.dialog.tsx
  dashboard/src/features/nodes/services/settings.mutate.ts
Labels: bug

#249 fix: 422 error is shown as reference to request failure to api
  app/routes/inbounds.py
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/features/hosts/dialogs/mutation/fields/address.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/allow-insecure.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/alpn.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/fingerprint.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/host.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/index.ts
  dashboard/src/features/hosts/dialogs/mutation/fields/path.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/port.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/remark.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/security.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/sni.tsx
  dashboard/src/features/hosts/dialogs/mutation/index.tsx
  dashboard/src/features/hosts/schema/get-default.ts
  dashboard/src/features/hosts/schema/hosts-schema.ts
  dashboard/src/features/hosts/services/host-mutation.dto.ts
  dashboard/src/features/hosts/services/update-host.mutate.ts
  dashboard/src/features/hosts/tables/inbound-hosts/inbound-not-selected-alert-dialog.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/index.tsx
Labels: bug

#258 fix(users): calculate gigabyte instead of raw byte in data limit field of user
  dashboard/src/features/users/constants.ts
  dashboard/src/features/users/dialogs/mutation/fields/services.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
  dashboard/src/features/users/dialogs/mutation/schema.ts
  dashboard/src/features/users/index.ts
  dashboard/src/hooks/use-mutation-dialog/index.ts
Labels: bug

#261 improve(nodes): well sized and position for nodes configuration save button
  dashboard/src/features/nodes/dialogs/settings.dialog.tsx
Labels: improvement

#262 fix(nodes): enable scrolling for nodes settings dialog
  dashboard/src/features/nodes/dialogs/settings.dialog.tsx
Labels: improvement

#259 improved: marzneshin feature list
  README.md
Labels: documentation

#265 fix(nodes-config-editor): json validation node config editor
  dashboard/src/features/nodes/dialogs/index.ts
  dashboard/src/features/nodes/dialogs/settings.dialog.tsx
  dashboard/src/features/nodes/dialogs/settings/index.tsx
  dashboard/src/features/nodes/dialogs/settings/node-config-editor.tsx
  dashboard/src/features/nodes/dialogs/settings/use-nodes-settings.ts
Labels: bug, frontend

#264 fix(users-mutation-dialog): user mutation switch onhold infinite refresh and invalid API request
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/features/users/dialogs/mutation/fields/data-limit.tsx
  dashboard/src/features/users/dialogs/mutation/fields/index.ts
  dashboard/src/features/users/dialogs/mutation/fields/onhold-expire-duration.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
  dashboard/src/features/users/dialogs/mutation/sections/data-limit.tsx
  dashboard/src/features/users/dialogs/mutation/sections/expiration-method.tsx
  dashboard/src/features/users/dialogs/mutation/sections/index.ts
  dashboard/src/features/users/dialogs/mutation/sections/use-expiration-method-tabs.ts
Labels: frontend

#267 improve(users-username-edit): disable username field while editing username
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/features/users/dialogs/mutation/fields/onhold-expire-duration.tsx
  dashboard/src/features/users/dialogs/mutation/fields/username.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: improvement, frontend

#239 feat(dashboard): users statistics
  app/db/crud.py
  app/models/system.py
  app/routes/system.py
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/components/stats-widgets/index.ts
  dashboard/src/components/stats-widgets/mini-widget/index.tsx
  dashboard/src/features/users/components/table-row-with-cell.tsx
  dashboard/src/features/users/index.ts
  dashboard/src/features/users/services/users-stats.query.ts
  dashboard/src/features/users/widgets/index.ts
  dashboard/src/features/users/widgets/users-stats-widget/index.tsx
  dashboard/src/features/users/widgets/users-stats-widget/legend.tsx
  dashboard/src/routeTree.gen.ts
  dashboard/src/routes/_dashboard/hosts.tsx
  dashboard/src/routes/_dashboard/index.tsx
  dashboard/src/routes/_dashboard/nodes.tsx
  dashboard/src/routes/_dashboard/services.tsx
  dashboard/src/routes/_dashboard/settings.tsx
  dashboard/src/routes/_dashboard/users.tsx
Labels: enhancement, good first issue, frontend, backend

#274 feat(hosts-popover-guideline): popover guide for remark
  dashboard/public/locales/en.json
  dashboard/src/features/hosts/dialogs/mutation/fields/popover-guide.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/remark.tsx
Labels: enhancement, frontend

#275 fix: nullable hosts field for optional fields
  dashboard/src/features/hosts/dialogs/mutation/fields/remark.tsx
  dashboard/src/features/hosts/schema/hosts-schema.ts
  dashboard/src/features/hosts/tables/inbound-hosts/index.tsx
Labels: bug

#276 improve(fetching): loader indicator while fetching query
  dashboard/src/components/entity-table/table.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/index.tsx
  dashboard/src/features/hosts/tables/inbound-hosts/table.tsx
Labels: improvement, frontend

#278 feat(users): pretty byte is shown in kibibyte format
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/src/features/users/components/used-user-traffic.tsx
Labels: bug

#279 feat(hosts): mux and fragment
  app/db/crud.py
  app/db/migrations/versions/74e234a3bd4b_add_mux_fragment_to_hosts.py
  app/db/models.py
  app/models/proxy.py
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/locales/en.json
  dashboard/public/locales/kur.json
  dashboard/src/components/entity-table/hooks/use-dialog.ts
  dashboard/src/components/entity-table/index.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/stacks/horizontal.tsx
  dashboard/src/components/stacks/index.ts
  dashboard/src/components/stacks/vertical.tsx
  dashboard/src/components/ui/accordion.tsx
  dashboard/src/components/ui/index.ts
  dashboard/src/features/hosts/dialogs/mutation/fields/alpn.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/fingerprint.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/fragment.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/host.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/index.ts
  dashboard/src/features/hosts/dialogs/mutation/fields/mux.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/path.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/security.tsx
  dashboard/src/features/hosts/dialogs/mutation/index.tsx
  dashboard/src/features/hosts/schema/get-default.ts
  dashboard/src/features/hosts/schema/hosts-schema.ts
  dashboard/src/features/hosts/tables/inbound-hosts/index.tsx
  dashboard/src/globals.css
  dashboard/src/hooks/index.ts
  dashboard/src/hooks/use-dialog.ts
Labels: feature, improvement, frontend, backend

#294 improve: translations
  dashboard/biome.json
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/public/locales/kur.json
  dashboard/src/components/header/index.tsx
  dashboard/src/features/auth/logout/index.tsx
  dashboard/src/features/language-switch/index.tsx
  dashboard/src/features/theme-switch/theme-toggle/index.tsx
  dashboard/src/features/users/dialogs/mutation/fields/note.tsx
Labels: improvement, frontend

#297 fix(nodes-log): node settings messes up when xray logs are too long
  dashboard/src/features/nodes/dialogs/settings/index.tsx
  dashboard/src/features/nodes/log/container.tsx
Labels: bug, frontend

#298 fix: user sheet isn't looking good on small screens
  dashboard/public/locales/en.json
  dashboard/src/components/copy-button/index.tsx
  dashboard/src/components/stacks/horizontal.tsx
  dashboard/src/features/users/dialogs/settings/index.tsx
  dashboard/src/features/users/dialogs/settings/user-info/qrcode.tsx
  dashboard/src/features/users/dialogs/settings/user-info/subcription-link-button.tsx
  dashboard/src/features/users/dialogs/settings/user-info/subscription-actions.tsx
  dashboard/src/features/users/dialogs/settings/user-info/table.tsx
Labels: bug, frontend

#296 fix(users-dialog): user creation dialog not responsive
  dashboard/src/components/stacks/vertical.tsx
  dashboard/src/features/services/dialogs/mutation.dialog.tsx
  dashboard/src/features/users/dialogs/mutation/fields/services.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: bug, frontend

#301 fix(subscription-link): icon disapperance
  dashboard/src/components/copy-button/index.tsx
  dashboard/src/features/users/tables/users/columns.tsx
Labels: bug, frontend

#300 fix(hosts-mutation-dialog): create/edit host dialog isn't responsive
  dashboard/src/features/hosts/dialogs/mutation/fields/fragment.tsx
  dashboard/src/features/hosts/dialogs/mutation/index.tsx
  dashboard/src/features/users/dialogs/mutation/index.tsx
Labels: bug, frontend, mobile, ui-responsive

#306 fix: provide write all permission
  .github/workflows/package.yml
Labels: invalid, continuous-integration

#308 improve(nodes-log): light theme log separation
  dashboard/src/features/nodes/log/container.tsx
Labels: improvement, frontend

#304 fix: users pagination initial state must be 1
  dashboard/src/components/entity-table/hooks/use-entity-table.ts
  dashboard/src/components/entity-table/table-pagination.tsx
Labels: bug, frontend

#309 feat(nodes-dialog): removing add as host and nodes backend connection
  app/db/crud.py
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/public/locales/kur.json
  dashboard/src/features/nodes/dialogs/mutation.dialog.tsx
  dashboard/src/features/nodes/types/index.ts
Labels: feature, frontend

#313 remove: sidebar tooltip on collapsed
  dashboard/src/features/sidebar/sidebar.tsx
Labels: invalid, improvement, frontend

#282 refactor: simplify subscription codebase
  app/routes/subscription.py
  app/utils/keygen.py
  app/utils/share.py
  requirements.txt
Labels: refactor, backend

#319 feat: store node stats
  app/tasks/record_usages.py
  app/tasks/reset_user_data_usage.py
Labels: backend

#321 refact(dashboard): resolving code smells and unreliable code
  dashboard/src/components/entity-table/index.tsx
  dashboard/src/features/services/dialogs/index.ts
  dashboard/src/features/services/dialogs/mutation.dialog.tsx
  dashboard/src/features/services/dialogs/mutation/fields/inbounds.tsx
  dashboard/src/features/services/dialogs/mutation/fields/index.ts
  dashboard/src/features/services/dialogs/mutation/fields/name.tsx
  dashboard/src/features/services/dialogs/mutation/index.tsx
  dashboard/src/features/services/tables/inbounds/index.tsx
  dashboard/src/features/users/dialogs/mutation/fields/services.tsx
  dashboard/src/features/users/dialogs/mutation/fields/username.tsx
  dashboard/src/features/users/tables/services/index.tsx
Labels: refactor

#312 fix(entity-table): 0th pagination
  dashboard/src/components/entity-table/hooks/use-entity-table.ts
  dashboard/src/components/entity-table/table-pagination.tsx
Labels: bug, frontend

#320 feat: advertise header-type and reality settings in configs
  app/utils/share.py
  app/utils/store.py
Labels: feature
