Repository marzneshin/marzneshin, pull requests merged in 2024-03, with the labels that each got.

#121 fix: refetch query invalidation #107
  app/dashboard/src/constants/query-ids.ts
  app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx
  app/dashboard/src/pages/hosts/users/dialog/data-limit-field.tsx
  app/dashboard/src/pages/hosts/users/dialog/default-values.ts
  app/dashboard/src/pages/hosts/users/dialog/expire-date-field.tsx
  app/dashboard/src/pages/hosts/users/dialog/form-schema.ts
  app/dashboard/src/pages/hosts/users/dialog/icons.ts
  app/dashboard/src/pages/hosts/users/dialog/index.tsx
  app/dashboard/src/pages/hosts/users/dialog/note-field.tsx
  app/dashboard/src/pages/hosts/users/dialog/periodic-usage-reset.tsx
  app/dashboard/src/pages/hosts/users/dialog/services-field.tsx
  app/dashboard/src/pages/hosts/users/dialog/services-select-list.tsx
  app/dashboard/src/pages/hosts/users/dialog/username-field.tsx
  app/dashboard/src/pages/hosts/users/filters.tsx
  app/dashboard/src/pages/hosts/users/index.tsx
  app/dashboard/src/pages/hosts/users/modals/delete-modal.tsx
  app/dashboard/src/pages/hosts/users/modals/index.tsx
  app/dashboard/src/pages/hosts/users/modals/qrcode-modals.tsx
  app/dashboard/src/pages/hosts/users/modals/reset-all-usage-modal.tsx
  app/dashboard/src/pages/hosts/users/modals/reset-user-usage-modal.tsx
  app/dashboard/src/pages/hosts/users/modals/revoke-subscription-modal.tsx
  app/dashboard/src/pages/hosts/users/table/action-buttons.tsx
  app/dashboard/src/pages/hosts/users/table/index.tsx
  app/dashboard/src/pages/hosts/users/table/usage-slider.tsx
  app/dashboard/src/pages/nodes/table/index.tsx
  app/dashboard/src/pages/services/dialog/index.tsx
  app/dashboard/src/pages/services/table.tsx
  app/dashboard/src/pages/users/dialog/index.tsx
  app/dashboard/src/pages/users/table/index.tsx
  app/dashboard/src/stores/inbounds.store.ts
  app/dashboard/src/stores/nodes.store.ts
  app/dashboard/src/stores/services.store.ts
  app/dashboard/src/stores/users.store.ts
  makefile
Labels: bug

#122 fix: migrate tanstack query v5 hosts table
  app/dashboard/package-lock.json
  app/dashboard/package.json
  app/dashboard/src/index.tsx
  app/dashboard/src/pages/home/statistics.tsx
  app/dashboard/src/pages/hosts/container.tsx
  app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx
  app/dashboard/src/pages/hosts/table/index.tsx
  app/dashboard/src/pages/nodes/modals/core-settings-modal.tsx
  app/dashboard/src/pages/nodes/table/index.tsx
  app/dashboard/src/pages/services/dialog/index.tsx
  app/dashboard/src/pages/services/table.tsx
  app/dashboard/src/pages/users/dialog/index.tsx
  app/dashboard/src/pages/users/table/index.tsx
  app/dashboard/src/service/react-query.ts
  app/dashboard/src/stores/inbounds.store.ts
  app/dashboard/src/stores/nodes.store.ts
  app/dashboard/src/stores/services.store.ts
  app/dashboard/src/stores/users.store.ts
  makefile
Labels: bug, invalid, frontend

#123 fix: undefined request arg, statistics rerender
  app/dashboard/public/locales/en.json
  app/dashboard/src/components/table/empty-section.tsx
  app/dashboard/src/pages/home/statistics.tsx
  app/dashboard/src/pages/hosts/filters.tsx
  app/dashboard/src/pages/hosts/table/index.tsx
  app/dashboard/src/stores/inbounds.store.ts
Labels: bug, frontend

#125 fix(hosts-table): assigned value never used
  app/dashboard/src/pages/hosts/table/index.tsx
Labels: invalid, continuous-integration, task, frontend

#129 fix: hosts dialog crash
  app/dashboard/package-lock.json
  app/dashboard/src/pages/hosts/container.tsx
  app/dashboard/src/pages/hosts/dialog/default-values.ts
  app/dashboard/src/pages/hosts/dialog/index.tsx
  app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx
  app/dashboard/src/pages/hosts/table/index.tsx
  app/dashboard/src/stores/inbounds.store.ts
Labels: bug

#130 improv(hosts-page): correct refetching, callout, pre-selecting at page startup
  app/dashboard/index.html
  app/dashboard/public/locales/en.json
  app/dashboard/src/components/callout/index.tsx
  app/dashboard/src/pages/hosts/container.tsx
  app/dashboard/src/pages/hosts/dialog/default-values.ts
  app/dashboard/src/pages/hosts/dialog/index.tsx
  app/dashboard/src/pages/hosts/inbounds-sidebar/index.tsx
  app/dashboard/src/pages/nodes/dialog.tsx
  app/dashboard/src/stores/inbounds.store.ts
  makefile
Labels: bug, improvement, frontend

#139 feat: Marznode Logs and configuration
  app/dashboard/package-lock.json
  app/dashboard/src/pages/nodes/index.tsx
  app/dashboard/src/pages/nodes/modals/core-settings/content.tsx
  app/dashboard/src/pages/nodes/modals/core-settings/helper.ts
  app/dashboard/src/pages/nodes/modals/core-settings/icon.tsx
  app/dashboard/src/pages/nodes/modals/core-settings/index.tsx
  app/dashboard/src/pages/nodes/table/action-buttons.tsx
  app/dashboard/src/pages/nodes/table/index.tsx
  app/dashboard/src/stores/core-settings.store.ts
  app/dashboard/src/stores/nodes.store.ts
  app/db/crud.py
  app/marznode/grpcio.py
  app/marznode/grpclib.py
  app/marznode/marznode.proto
  app/marznode/marznode_grpc.py
  app/marznode/marznode_pb2.py
  app/marznode/marznode_pb2.pyi
  app/marznode/marznode_pb2_grpc.py
  app/routes/node.py
Labels: enhancement, frontend, backend

#143 feat: Painless deployment
  app/db/migrations/versions/20faa9f18c0a_init.py
  docker-compose.yml
  script.sh
Labels: improvement, continuous-deployment

#144 feat: api pagination
  app/marzneshin.py
  app/models/node.py
  app/models/user.py
  app/routes/admin.py
  app/routes/inbounds.py
  app/routes/node.py
  app/routes/service.py
  app/routes/system.py
  app/routes/user.py
Labels: enhancement, refactor, improvement, backend

#160 feat: dashboard rewrite setup and theme switch
  dashboard/.eslintrc.cjs
  dashboard/.gitignore
  dashboard/README.md
  dashboard/components.json
  dashboard/index.html
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/postcss.config.js
  dashboard/public/.gitkeep
  dashboard/src/app.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/ui/alert-dialog.tsx
  dashboard/src/components/ui/alert.tsx
  dashboard/src/components/ui/badge.tsx
  dashboard/src/components/ui/breadcrumb.tsx
  dashboard/src/components/ui/button.tsx
  dashboard/src/components/ui/card.tsx
  dashboard/src/components/ui/checkbox.tsx
  dashboard/src/components/ui/collapsible.tsx
  dashboard/src/components/ui/dialog.tsx
  dashboard/src/components/ui/drawer.tsx
  dashboard/src/components/ui/dropdown-menu.tsx
  dashboard/src/components/ui/form.tsx
  dashboard/src/components/ui/index.ts
  dashboard/src/components/ui/input.tsx
  dashboard/src/components/ui/label.tsx
  dashboard/src/components/ui/popover.tsx
  dashboard/src/components/ui/resizable.tsx
  dashboard/src/components/ui/separator.tsx
  dashboard/src/components/ui/sonner.tsx
  dashboard/src/components/ui/switch.tsx
  dashboard/src/components/ui/table.tsx
  dashboard/src/components/ui/toggle.tsx
  dashboard/src/components/ui/tooltip.tsx
  dashboard/src/features/theme-switch/index.ts
  dashboard/src/features/theme-switch/theme-provider.tsx
  dashboard/src/features/theme-switch/theme-toggle/index.tsx
  dashboard/src/globals.css
  dashboard/src/routeTree.gen.ts
  dashboard/src/routes/__root.tsx
  dashboard/src/routes/_auth.tsx
  dashboard/src/routes/_dashboard.tsx
  dashboard/src/routes/_dashboard/index.tsx
  dashboard/src/routes/index.lazy.tsx
  dashboard/src/utils.ts
  dashboard/src/vite-env.d.ts
  dashboard/tailwind.config.js
  dashboard/tsconfig.json
  dashboard/tsconfig.node.json
  dashboard/vite.config.ts
Labels: enhancement, task, frontend

#163 feat(ui-rewrite): internationalization
  .gitignore
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/locales/en.json
  dashboard/src/app.tsx
  dashboard/src/features/i18n/index.ts
  dashboard/src/routes/index.lazy.tsx
  dashboard/src/utils/cn.ts
  dashboard/src/utils/index.ts
  dashboard/tsconfig.json
Labels: enhancement, refactor, frontend

#164 ci: adapt new ui rewrite
  .github/workflows/dashboard-ci.yml
  dashboard/.eslintrc.cjs
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/src/app.tsx
  dashboard/src/features/i18n/index.ts
  dashboard/tsconfig.json
  dashboard/vite.config.ts
Labels: bug, continuous-integration

#165 feat(login-page): login form for authentication - new ui rewrite
  app/marzneshin.py
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/locales/en.json
  dashboard/src/components/ui/aspect-ratio.tsx
  dashboard/src/components/ui/index.ts
  dashboard/src/features/auth/auth.store.ts
  dashboard/src/features/auth/index.ts
  dashboard/src/features/auth/login/form-error.tsx
  dashboard/src/features/auth/login/form.tsx
  dashboard/src/features/auth/login/index.ts
  dashboard/src/features/auth/login/schema.ts
  dashboard/src/globals.css
  dashboard/src/routeTree.gen.ts
  dashboard/src/routes/_auth.tsx
  dashboard/src/routes/_auth/login.tsx
  dashboard/src/routes/_dashboard.tsx
  dashboard/src/routes/_dashboard/index.tsx
  dashboard/src/routes/index.lazy.tsx
  dashboard/src/utils/fetch.ts
  dashboard/src/utils/index.ts
  dashboard/tailwind.config.js
Labels: enhancement, continuous-integration, frontend

#167 feat(dashboard): dashboard layout with responsive and collapsible sidebar, header, theme toggle
  .github/workflows/dashboard-ci.yml
  dashboard/.eslintrc.cjs
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/src/components/header/index.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/nav-dir/index.tsx
  dashboard/src/components/sidebar/index.ts
  dashboard/src/components/sidebar/sidebar-body.tsx
  dashboard/src/components/sidebar/sidebar-footer.tsx
  dashboard/src/components/sidebar/sidebar-group.tsx
  dashboard/src/components/sidebar/sidebar-header.tsx
  dashboard/src/components/sidebar/sidebar-item.tsx
  dashboard/src/components/sidebar/sidebar-provider.tsx
  dashboard/src/components/sidebar/sidebar-title.tsx
  dashboard/src/components/sidebar/sidebar.tsx
  dashboard/src/components/sidebar/types.ts
  dashboard/src/components/ui/radio-group.tsx
  dashboard/src/features/sidebar/index.ts
  dashboard/src/features/sidebar/items.tsx
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/src/features/sidebar/toggle.tsx
  dashboard/src/features/sidebar/use-panel-toggle.ts
  dashboard/src/features/theme-switch/theme-toggle/index.tsx
  dashboard/src/hooks/index.ts
  dashboard/src/hooks/use-screen-breakpoint.ts
  dashboard/src/routeTree.gen.ts
  dashboard/src/routes/_auth.tsx
  dashboard/src/routes/_dashboard.tsx
  dashboard/src/routes/_dashboard/hosts.tsx
  dashboard/src/routes/_dashboard/nodes.tsx
  dashboard/src/routes/_dashboard/services.tsx
  dashboard/src/routes/_dashboard/users.tsx
  dashboard/src/types/index.ts
Labels: enhancement

#168 improve(login-form): refine username and password fields
  dashboard/src/features/auth/login/form.tsx
Labels: improvement, frontend

#169 feat(nodes): nodes page
  dashboard/index.html
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/public/locales/en.json
  dashboard/src/components/data-table/actions-cell.tsx
  dashboard/src/components/data-table/column-header.tsx
  dashboard/src/components/data-table/index.ts
  dashboard/src/components/data-table/pagination.tsx
  dashboard/src/components/data-table/table-view-option.tsx
  dashboard/src/components/data-table/table.tsx
  dashboard/src/components/delete-confirmation-dialog/index.tsx
  dashboard/src/components/header/index.tsx
  dashboard/src/components/index.ts
  dashboard/src/components/nav-dir/index.tsx
  dashboard/src/components/sidebar/sidebar-body.tsx
  dashboard/src/components/ui/form.tsx
  dashboard/src/components/ui/index.ts
  dashboard/src/components/ui/scroll-area.tsx
  dashboard/src/components/ui/select.tsx
  dashboard/src/components/ui/sheet.tsx
  dashboard/src/components/ui/tabs.tsx
  dashboard/src/features/nodes/dialogs/delete-confirmation.dialog.tsx
  dashboard/src/features/nodes/dialogs/index.ts
  dashboard/src/features/nodes/dialogs/mutation.dialog.tsx
  dashboard/src/features/nodes/dialogs/settings.dialog.tsx
  dashboard/src/features/nodes/index.ts
  dashboard/src/features/nodes/log/container.tsx
  dashboard/src/features/nodes/log/index.ts
  dashboard/src/features/nodes/services/create-node.mutate.ts
  dashboard/src/features/nodes/services/delete-node.mutate.ts
  dashboard/src/features/nodes/services/index.ts
  dashboard/src/features/nodes/services/logs.socket.ts
  dashboard/src/features/nodes/services/nodes.query.ts
  dashboard/src/features/nodes/services/settings.mutate.ts
  dashboard/src/features/nodes/services/settings.query.ts
  dashboard/src/features/nodes/services/update-node.mutate.ts
  dashboard/src/features/nodes/tables/columns.tsx
  dashboard/src/features/nodes/tables/detail-table/index.tsx
  dashboard/src/features/nodes/tables/index.ts
  dashboard/src/features/nodes/tables/nodes-status-badge.tsx
  dashboard/src/features/nodes/tables/table.tsx
  dashboard/src/features/nodes/types/index.ts
  dashboard/src/features/settings/certificate-button/index.tsx
  dashboard/src/features/settings/index.ts
  dashboard/src/features/settings/services/certificate.query.ts
  dashboard/src/features/settings/services/index.ts
  dashboard/src/features/sidebar/items.tsx
  dashboard/src/features/sidebar/sidebar.tsx
  dashboard/src/features/sidebar/toggle.tsx
  dashboard/src/features/theme-switch/theme-toggle/index.tsx
  dashboard/src/hooks/index.ts
  dashboard/src/hooks/use-screen-breakpoint.ts
  dashboard/src/routeTree.gen.ts
  dashboard/src/routes/__root.tsx
  dashboard/src/routes/_dashboard.tsx
  dashboard/src/routes/_dashboard/nodes.tsx
  dashboard/src/routes/_dashboard/settings.tsx
  dashboard/src/utils/index.ts
  dashboard/src/utils/query-client.ts
Labels: frontend

#174 fix: minor UI dialog bug
  dashboard/src/features/nodes/dialogs/mutation.dialog.tsx
  dashboard/src/features/sidebar/sidebar.tsx
Labels: bug, improvement, frontend

#175 improve(nodes-config): style json output of the editor
  dashboard/src/features/nodes/dialogs/settings.dialog.tsx
Labels: improvement, frontend
