Repository marzneshin/marzneshin, pull requests merged in 2024-12, with the labels that each got.

#685 feat(hosts/shadowtls): host profile for shadowtls
  dashboard/src/modules/hosts/dialogs/mutation/profiles/shadowtls/default.ts
  dashboard/src/modules/hosts/dialogs/mutation/profiles/shadowtls/index.tsx
  dashboard/src/modules/hosts/dialogs/mutation/profiles/shadowtls/schema.ts
  dashboard/src/modules/hosts/dialogs/mutation/profiles/use-profile-strategy.ts
  dashboard/src/modules/inbounds/types/index.ts
Labels: feature, frontend

#686 fix(tuic-hosts): wrapping the tuic profile fields in accordian
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/src/modules/hosts/dialogs/mutation/profiles/tuic/index.tsx
Labels: bug, frontend

#694 fix(settings/subscription): removin v2ray from subscription options
  dashboard/src/modules/settings/subscription/form/rule-item.tsx
  dashboard/src/modules/settings/subscription/form/schema.ts
  dashboard/src/modules/settings/subscription/subscription-rule.type.ts
Labels: bug, frontend

#697 fix(release-version): the release indicator shouldn't disappear when the height gets smaller
  dashboard/src/routes/_dashboard.tsx
Labels: bug, frontend

#695 fix(users/data-limit): toggling data limit woudn't make the user unlimited
  dashboard/src/modules/users/components/dialogs/mutation/sections/data-limit/use-data-limit.ts
Labels: bug, frontend

#703 feat(admins/enable-disable-users): disable and enable all admin's user
  app/routes/admin.py
  dashboard/public/locales/en.json
  dashboard/src/modules/admins/api/disable-admin-users.mutate.ts
  dashboard/src/modules/admins/api/enable-admin-users.mutate.ts
  dashboard/src/modules/admins/api/index.ts
  dashboard/src/modules/admins/components/dialogs/settings/admin-info/table.tsx
Labels: feature, improvement, frontend, backend

#706 fix(users-subscription/qrcode): adding white background to QRCode to be recognized
  dashboard/src/modules/users/components/dialogs/settings/user-info/qrcode.tsx
Labels: bug, frontend

#698 fix(service/userids): add user removed check
  app/db/models.py
Labels: backend

#714 improve(version-indicator): relocating its location and removing the marzneshin name
  dashboard/src/common/components/header/menu.tsx
  dashboard/src/features/language-switch/index.tsx
  dashboard/src/features/theme-switch/theme-toggle/index.tsx
  dashboard/src/features/version-indicator/index.tsx
  dashboard/src/modules/auth/logout/index.tsx
  dashboard/src/routes/_dashboard.tsx
Labels: improvement, frontend, user-experience

#573 feat(notification): implement a unified notification system
  app/db/__init__.py
  app/db/crud.py
  app/db/migrations/versions/20241127_79271458a973_drop_notification_reminders_table.py
  app/db/models.py
  app/marzneshin.py
  app/marznode/base.py
  app/models/notification.py
  app/models/user.py
  app/notification/__init__.py
  app/notification/factory.py
  app/notification/helper.py
  app/notification/notifiers.py
  app/notification/services.py
  app/notification/telegram.py
  app/notification/webhook.py
  app/routes/user.py
  app/tasks/__init__.py
  app/tasks/data_usage_percent_reached.py
  app/tasks/expire_days_reached.py
  app/tasks/record_usages.py
  app/tasks/review_users.py
  app/tasks/send_notifications.py
  app/telegram/__init__.py
  app/telegram/report.py
  app/utils/helpers.py
  app/utils/notification.py
  app/utils/report.py
  app/utils/share.py
  app/webhooks.py
  requirements.txt
Labels: backend

#712 refact(dep/service): add get_service dep
  app/dependencies.py
  app/routes/service.py
Labels: refactor, backend

#759 fix(dashboard): allow user data limit to be float in GB in user mutation
  dashboard/src/modules/users/domain/schema.ts
Labels: bug, frontend

#761 fix(hosts): port validation
  dashboard/src/modules/hosts/domain/host.ts
Labels: bug, improvement, frontend

#762 improve(hosts/noise): noise schema and field organization
  dashboard/src/modules/hosts/dialogs/mutation/fields/noise.tsx
  dashboard/src/modules/hosts/dialogs/mutation/profiles/general/index.tsx
  dashboard/src/modules/hosts/dialogs/mutation/profiles/general/schema.ts
Labels: improvement, frontend, feat:hosts

#763 improve(i18n): Set html lang attribute based on language change
  dashboard/src/features/i18n/index.ts
Labels: improvement, frontend, translation
