Repository marzneshin/marzneshin, pull requests merged in 2024-11, with the labels that each got.

#621 feat(inbounds): extend proxy types
  app/db/migrations/versions/b613375d2fca_add_new_protocols_to_proxytypes_enum.py
  app/models/proxy.py
  app/routes/subscription.py
  app/utils/share.py
  requirements.txt
Labels: backend

#630 fix(users-admins-modules): no initial data required for query options
  dashboard/src/modules/admins/api/admin.query.ts
  dashboard/src/modules/users/api/queries/user.query.ts
  dashboard/src/modules/users/components/dialogs/settings/index.tsx
Labels: bug, improvement, ci, frontend

#634 fix(hosts-inbounds-table): fixed height for inbound cards
  dashboard/src/libs/entity-table/components/sidebar-entity-selection.tsx
Labels: bug, frontend

#642 fix(hosts/is-disabled): adding is disabled field for other profiles in schema
  dashboard/.storybook/preview.tsx
  dashboard/src/modules/hosts/dialogs/mutation/profiles/hysteria2/default.ts
  dashboard/src/modules/hosts/dialogs/mutation/profiles/hysteria2/schema.ts
  dashboard/src/modules/hosts/dialogs/mutation/profiles/wireguard/default.ts
  dashboard/src/modules/hosts/dialogs/mutation/profiles/wireguard/schema.ts
Labels: bug, frontend

#660 feat(alembic): Include date in migration file names
  alembic.ini
  app/db/migrations/versions/20240115_20faa9f18c0a_init.py
  app/db/migrations/versions/20240501_e8325f600a49_user_enable.py
  app/db/migrations/versions/20240522_74e234a3bd4b_add_mux_fragment_to_hosts.py
  app/db/migrations/versions/20240526_058eb11c5b17_user_reset_in_table.py
  app/db/migrations/versions/20240608_9001356f0063_create_settings.py
  app/db/migrations/versions/20240627_a83e4dd22672_refactor_user_expire.py
  app/db/migrations/versions/20240708_3acfdeb79b78_add_admin_services.py
  app/db/migrations/versions/20240714_b0357faf51c8_add_removed_to_users.py
  app/db/migrations/versions/20240724_5410d8ec78ff_alpn_to_string.py
  app/db/migrations/versions/20240728_c4fb5f6423a8_add_hysteria2_protocol_for_inbounds.py
  app/db/migrations/versions/20240801_35774c98f945_add_node_backends.py
  app/db/migrations/versions/20240807_fd423c19f682_add_weight_to_host.py
  app/db/migrations/versions/20241009_1992c49c5990_add_sub_revoked_at.py
  app/db/migrations/versions/20241029_b613375d2fca_add_new_protocols_to_proxytypes_enum.py
  app/db/migrations/versions/20241103_c97bd32e6e12_add_noises_to_hosts.py
  app/db/migrations/versions/20241111_be0032100c07_add_allowed_ips_to_hosts.py
Labels: improvement, backend
