Repository marzneshin/marzneshin, pull requests merged in 2024-07, with the labels that each got.

#408 improve(service-creation): scrollable inbounds
  dashboard/src/features/services/dialogs/mutation/fields/inbounds.tsx
Labels: bug, improvement, frontend

#415 fix(remove-settings-for-none-sudo): removign settings button on mobile for non-sudo admin
  dashboard/src/features/bottom-menu/index.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
  dashboard/src/routes/_dashboard.tsx
Labels: improvement, frontend, mobile, user-experience

#419 fix(hosts-inbounds): refetch hosts inbounds
  dashboard/src/features/hosts/services/create-host.mutate.ts
  dashboard/src/features/hosts/services/delete-host.mutate.ts
  dashboard/src/features/hosts/services/update-host.mutate.ts
Labels: bug, improvement, frontend

#420 improve(translation): missing translations & and sorani latin
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/public/locales/kur.json
  dashboard/src/components/data-table/table-view-option.tsx
  dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
  dashboard/src/features/settings/widgets/certificate.tsx
Labels: frontend, translation

#424 improve(users-table): removing enabled column
  dashboard/src/features/users/components/tables/users/columns.tsx
Labels: improvement, frontend

#426 fix(users-info): 'expired' translation token
  dashboard/src/features/users/components/dialogs/settings/user-info/table.tsx
  dashboard/src/features/users/components/pills/user-expired-pill.tsx
Labels: bug

#428 fix(hosts-inbound-table): scrolling on lower sized page
  dashboard/src/features/entity-table/components/sidebar-entity-selection.tsx
Labels: bug, frontend, feat:data-entity-table

#432 fix(node-updates): make sure user object is independent to db session
  app/marznode/operations.py
Labels: bug, backend

#436 fix(entity-table): stacking view options and create button on filter for mobile
  dashboard/src/features/entity-table/components/table-filtering.tsx
  dashboard/src/features/entity-table/entity-table.tsx
Labels: improvement, frontend, mobile, responsiveness

#439 improve(translation): persian for admin management
  dashboard/public/locales/fa.json
Labels: translation

#440 fix(access-management): sudo admins have access to services
  app/routes/service.py
Labels: bug, backend

#441 feat(user-management): users soft delete
  app/db/crud.py
  app/db/migrations/versions/b0357faf51c8_add_removed_to_users.py
  app/db/models.py
  app/routes/user.py
Labels: feature, refactor, backend

#447 fix(users-data-limit): metric conversion after type conversion
  dashboard/src/features/users/types/schema.ts
Labels: bug, improvement, frontend

#448 fix(subscription): set subscription headers to 0 when null for better representation in hiddify
  app/routes/subscription.py
Labels: improvement, backend

#449 feat(header-menu): including settings and admins page in menu for sudo admins in mobile view
  dashboard/src/components/header/menu.tsx
  dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/index.tsx
  dashboard/src/routes/_dashboard.tsx
Labels: feature, frontend, feat:multiadmin

#451 feat(CI/CD): added a Dockerfile for previewing PR's and testing.
  Dockerfile.preview
Labels: ci, cd

#455 fix(expire-strategy): load fixed date
  dashboard/src/features/admins/components/dialogs/mutation/index.tsx
  dashboard/src/features/github-repo/github-repo.stories.tsx
  dashboard/src/features/github-repo/github-repo.tsx
  dashboard/src/features/github-repo/index.ts
  dashboard/src/features/github-repo/services/github-repo.query.ts
  dashboard/src/features/hosts/dialogs/mutation/index.tsx
  dashboard/src/features/nodes/dialogs/mutation/index.tsx
  dashboard/src/features/services/components/dialogs/mutation/index.tsx
  dashboard/src/features/users/components/dialogs/mutation/index.tsx
  dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/expiration-method.strategy.ts
  dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/index.tsx
  dashboard/src/features/users/components/dialogs/mutation/sections/expiration-method/use-expiration-method-tabs.ts
  dashboard/src/features/users/components/index.ts
  dashboard/src/features/users/components/no-service-alert/index.tsx
  dashboard/src/hooks/use-mutation-dialog/index.ts
  dashboard/src/routes/_dashboard.tsx
  dashboard/src/routes/_dashboard/admins/$adminId/edit.tsx
  dashboard/src/routes/_dashboard/admins/create.tsx
  dashboard/src/routes/_dashboard/hosts/$hostId/edit.tsx
  dashboard/src/routes/_dashboard/hosts/$inboundId/create.tsx
  dashboard/src/routes/_dashboard/nodes/$nodeId/edit.tsx
  dashboard/src/routes/_dashboard/nodes/create.tsx
  dashboard/src/routes/_dashboard/services/$serviceId/edit.tsx
  dashboard/src/routes/_dashboard/services/create.tsx
  dashboard/src/routes/_dashboard/users.lazy.tsx
  dashboard/src/routes/_dashboard/users/$userId/edit.tsx
  dashboard/src/routes/_dashboard/users/create.tsx
Labels: frontend

#458 feat(admins-usages-data-usage): admin's users data usage
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/src/features/admins/components/dialogs/settings/admin-info/table.tsx
  dashboard/src/features/admins/components/dialogs/settings/index.tsx
  dashboard/src/features/admins/types/admin.ts
Labels: feature, frontend, feat:multiadmin

#457 improve(admin-create-schema): admins password input and schema correction
  dashboard/src/features/admins/components/dialogs/mutation/fields/password.tsx
  dashboard/src/features/admins/components/dialogs/mutation/index.tsx
  dashboard/src/features/admins/types/schema.ts
Labels: bug, improvement, frontend, feat:multiadmin

#459 feat(hosts): disable and enable hosts for inbounds
  app/db/crud.py
  app/utils/share.py
  dashboard/src/components/form-fields/checkbox.tsx
  dashboard/src/components/form-fields/date.tsx
  dashboard/src/components/form-fields/index.ts
  dashboard/src/components/index.ts
  dashboard/src/features/hosts/dialogs/mutation/fields/is-disabled.tsx
  dashboard/src/features/hosts/dialogs/mutation/fields/remark.tsx
  dashboard/src/features/hosts/schema/get-default.ts
  dashboard/src/features/hosts/schema/hosts-schema.ts
  dashboard/src/features/subscription-settings/form/fields/index.ts
  dashboard/src/features/subscription-settings/form/fields/shuffle-configs.tsx
  dashboard/src/features/subscription-settings/form/fields/template-on-acceptance.tsx
  dashboard/src/features/subscription-settings/form/form.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/activation-deadline.tsx
  dashboard/src/features/users/components/dialogs/mutation/fields/expire-date.tsx
  dashboard/src/features/users/components/form-fields/index.ts
Labels: feature, frontend, backend

#434 feat(admin-management): displaying admin owner of user
  app/db/models.py
  app/models/user.py
  app/routes/user.py
  dashboard/public/locales/en.json
  dashboard/public/locales/fa.json
  dashboard/src/features/admins/components/tables/admins/index.tsx
  dashboard/src/features/entity-table/entity-table.tsx
  dashboard/src/features/entity-table/stories/entity-table.stories.tsx
  dashboard/src/features/entity-table/types/columns-sudo-visibility.ts
  dashboard/src/features/entity-table/types/index.ts
  dashboard/src/features/nodes/dialogs/mutation/index.tsx
  dashboard/src/features/nodes/tables/table.tsx
  dashboard/src/features/nodes/types/index.ts
  dashboard/src/features/services/components/tables/services/index.tsx
  dashboard/src/features/users/components/tables/users/columns.tsx
  dashboard/src/features/users/components/tables/users/index.tsx
Labels: frontend, backend, feat:multiadmin

#461 style(dashboard-sidebar): uppercase sidebar group items
  dashboard/src/components/sidebar/sidebar-group.tsx
  dashboard/src/features/sidebar/sidebar.tsx
Labels: improvement, frontend, user-experience

#460 chore(docs): readme multi admin feature
  README.md
Labels: docs

#465 fix(hosts): cast alpn to string in db
  app/db/crud.py
  app/db/migrations/versions/5410d8ec78ff_alpn_to_string.py
  app/db/models.py
  app/models/proxy.py
  app/utils/share.py
Labels: bug, backend

#466 feat(search-command): admins actions, scrollable, and create actions
  dashboard/src/features/search-command/command-box.tsx
  dashboard/src/features/search-command/command-items.tsx
  dashboard/src/features/search-command/commands.ts
Labels: feature, refactor, improvement, frontend, user-experience, feat:multiadmin

#470 feat(subscription): hysteria
  app/db/crud.py
  app/db/migrations/versions/c4fb5f6423a8_add_hysteria2_protocol_for_inbounds.py
  app/models/proxy.py
  app/utils/share.py
  requirements.txt
Labels: feature, backend
